# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.3.1
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.TTY/helloworld: "false"
    io.podman.annotations.autoremove/helloworld: "FALSE"
    io.podman.annotations.init/helloworld: "FALSE"
    io.podman.annotations.privileged/helloworld: "FALSE"
    io.podman.annotations.publish-all/helloworld: "FALSE"
  labels:
    app: helloworld-pod
  name: helloworld-pod
spec:
  automountServiceAccountToken: false
  containers:
  - image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0
    name: helloworld
    ports:
    - containerPort: 8080
      hostPort: 8080
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
  enableServiceLinks: false

